name: Destroy Infrastructure

on:
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI


jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: Production # Use GitHub Environments for protection/approvals

    env:
      # These override the defaults in variables.tf
      TF_VAR_environment: production
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_invoice_bucket_name: ${{ secrets.INVOICE_BUCKET_NAME }}
      TF_VAR_aws_ecs_cluster_name: ${{ secrets.INVOICE_GENERATOR_CLUSTER }}
      TF_VAR_aws_ecs_service_name: ${{ secrets.INVOICE_GENERATOR_SERVICE }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        # Assumes you have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY secrets
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./infra
        run: terraform destroy -auto-approve